package com.mini.ofbiz.core.model;

import java.util.Arrays;

/**
 * 实体元数据构建器
 * 提供流式API构建ModelEntity，方便单元测试和代码中动态创建实体模型
 */
public class EntityModelBuilder {

    /** 正在构建的实体 */
    private final ModelEntity entity;

    /** 当前正在操作的字段 */
    private ModelField currentField;

    /** 当前正在操作的索引 */
    private ModelIndex currentIndex;

    private EntityModelBuilder(String entityName, String tableName) {
        this.entity = new ModelEntity(entityName, tableName);
    }

    // ================== 静态工厂方法 ==================

    /**
     * 创建构建器
     *
     * @param entityName 实体名（Java风格）
     * @param tableName  表名（数据库风格）
     */
    public static EntityModelBuilder create(String entityName, String tableName) {
        return new EntityModelBuilder(entityName, tableName);
    }

    /**
     * 创建构建器（表名自动生成：entityName -> entity_name）
     */
    public static EntityModelBuilder create(String entityName) {
        String tableName = ModelField.nameToColName(entityName);
        return new EntityModelBuilder(entityName, tableName);
    }

    // ================== 字段定义 ==================

    /**
     * 添加普通字段
     */
    public EntityModelBuilder field(String name, String type) {
        finishCurrentField();
        currentField = new ModelField(name, type);
        // 如果是-ne后缀类型，自动设置非空
        if (FieldType.exists(type) && FieldType.fromSemantic(type).isNotNullByDefault()) {
            currentField.setNotNull(true);
        }
        return this;
    }

    /**
     * 添加带长度的字段
     */
    public EntityModelBuilder field(String name, String type, int length) {
        field(name, type);
        currentField.setLength(length);
        return this;
    }

    /**
     * 添加主键字段
     */
    public EntityModelBuilder pkField(String name) {
        finishCurrentField();
        currentField = new ModelField(name, "id-ne");
        currentField.setPk(true);
        currentField.setNotNull(true);
        return this;
    }

    /**
     * 添加自增主键字段
     */
    public EntityModelBuilder autoPkField(String name) {
        finishCurrentField();
        currentField = new ModelField(name, "id-ne");
        currentField.setPk(true);
        currentField.setNotNull(true);
        currentField.setAutoGenerated(true);
        return this;
    }

    /**
     * 添加指定类型的主键字段
     */
    public EntityModelBuilder pkField(String name, String type) {
        finishCurrentField();
        currentField = new ModelField(name, type);
        currentField.setPk(true);
        currentField.setNotNull(true);
        return this;
    }

    // ================== 字段属性设置 ==================

    /**
     * 设置当前字段非空
     */
    public EntityModelBuilder notNull() {
        if (currentField != null) {
            currentField.setNotNull(true);
        }
        return this;
    }

    /**
     * 设置当前字段默认值
     */
    public EntityModelBuilder defaultValue(String value) {
        if (currentField != null) {
            currentField.setDefaultValue(value);
        }
        return this;
    }

    /**
     * 设置当前字段描述
     */
    public EntityModelBuilder description(String desc) {
        if (currentField != null) {
            currentField.setDescription(desc);
        }
        return this;
    }

    /**
     * 设置当前字段为加密字段
     */
    public EntityModelBuilder encrypt() {
        if (currentField != null) {
            currentField.setEncrypt(true);
        }
        return this;
    }

    // ================== 索引定义 ==================

    /**
     * 添加普通索引
     */
    public EntityModelBuilder index(String... fieldNames) {
        finishCurrentField();
        finishCurrentIndex();

        String indexName = generateIndexName(false, fieldNames);
        currentIndex = new ModelIndex(indexName, false);
        currentIndex.addFieldNames(fieldNames);
        return this;
    }

    /**
     * 添加唯一索引
     */
    public EntityModelBuilder uniqueIndex(String... fieldNames) {
        finishCurrentField();
        finishCurrentIndex();

        String indexName = generateIndexName(true, fieldNames);
        currentIndex = new ModelIndex(indexName, true);
        currentIndex.addFieldNames(fieldNames);
        return this;
    }

    /**
     * 自定义索引名
     */
    public EntityModelBuilder indexName(String name) {
        if (currentIndex != null) {
            currentIndex.setName(name);
        }
        return this;
    }

    // ================== 实体属性 ==================

    /**
     * 设置包名
     */
    public EntityModelBuilder packageName(String packageName) {
        entity.setPackageName(packageName);
        return this;
    }

    /**
     * 设置描述
     */
    public EntityModelBuilder entityDescription(String desc) {
        entity.setDescription(desc);
        return this;
    }

    // ================== 构建 ==================

    /**
     * 构建ModelEntity
     */
    public ModelEntity build() {
        finishCurrentField();
        finishCurrentIndex();
        return entity;
    }

    // ================== 私有方法 ==================

    /**
     * 完成当前字段的构建
     */
    private void finishCurrentField() {
        if (currentField != null) {
            entity.addField(currentField);
            currentField = null;
        }
    }

    /**
     * 完成当前索引的构建
     */
    private void finishCurrentIndex() {
        if (currentIndex != null) {
            entity.addIndex(currentIndex);
            currentIndex = null;
        }
    }

    /**
     * 生成索引名
     */
    private String generateIndexName(boolean unique, String... fieldNames) {
        StringBuilder sb = new StringBuilder();
        sb.append(unique ? "UK_" : "IDX_");
        sb.append(entity.getTableName());
        for (String fn : fieldNames) {
            sb.append("_").append(fn);
        }
        return sb.toString();
    }

    @Override
    public String toString() {
        return "EntityModelBuilder{" +
                "entity=" + entity +
                ", currentField=" + currentField +
                '}';
    }
}
