package com.mini.ofbiz.core.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * 字段元数据模型
 * 描述单个字段的完整元数据
 */
public class ModelField implements Serializable {

    private static final long serialVersionUID = 1L;

    /** 字段名（Java风格，如 "userId"） */
    private String name;

    /** 列名（数据库风格，如 "user_id"） */
    private String colName;

    /** 语义类型（如 "id-ne", "name", "date-time"） */
    private String type;

    /** 是否主键 */
    private boolean isPk;

    /** 是否非空 */
    private boolean notNull;

    /** 默认值 */
    private String defaultValue;

    /** 字段长度 */
    private Integer length;

    /** 描述 */
    private String description;

    /** 是否自增主键 */
    private boolean isAutoGenerated;

    /** 是否可加密（密码等敏感字段） */
    private boolean encrypt;

    // ================== 构造方法 ==================

    public ModelField() {
    }

    public ModelField(String name, String type) {
        this.name = name;
        this.type = type;
        this.colName = nameToColName(name);
    }

    public ModelField(String name, String colName, String type) {
        this.name = name;
        this.colName = colName;
        this.type = type;
    }

    // ================== 工具方法 ==================

    /**
     * 将Java风格字段名转换为数据库列名
     * userId -> user_id, createTime -> create_time
     */
    public static String nameToColName(String fieldName) {
        if (fieldName == null || fieldName.isEmpty()) {
            return fieldName;
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < fieldName.length(); i++) {
            char c = fieldName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                sb.append('_');
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }

    /**
     * 将数据库列名转换为Java风格字段名
     * user_id -> userId, create_time -> createTime
     */
    public static String colNameToName(String colName) {
        if (colName == null || colName.isEmpty()) {
            return colName;
        }
        StringBuilder sb = new StringBuilder();
        boolean nextUpper = false;
        for (int i = 0; i < colName.length(); i++) {
            char c = colName.charAt(i);
            if (c == '_') {
                nextUpper = true;
            } else {
                if (nextUpper) {
                    sb.append(Character.toUpperCase(c));
                    nextUpper = false;
                } else {
                    sb.append(i == 0 ? Character.toLowerCase(c) : c);
                }
            }
        }
        return sb.toString();
    }

    // ================== 链式Setter ==================

    public ModelField name(String name) {
        this.name = name;
        return this;
    }

    public ModelField colName(String colName) {
        this.colName = colName;
        return this;
    }

    public ModelField type(String type) {
        this.type = type;
        return this;
    }

    public ModelField isPk(boolean isPk) {
        this.isPk = isPk;
        return this;
    }

    public ModelField notNull(boolean notNull) {
        this.notNull = notNull;
        return this;
    }

    public ModelField defaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
        return this;
    }

    public ModelField length(Integer length) {
        this.length = length;
        return this;
    }

    public ModelField description(String description) {
        this.description = description;
        return this;
    }

    public ModelField isAutoGenerated(boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
        return this;
    }

    public ModelField encrypt(boolean encrypt) {
        this.encrypt = encrypt;
        return this;
    }

    // ================== Getters & Setters ==================

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColName() {
        // 如果未设置列名，自动从字段名转换
        if (colName == null && name != null) {
            return nameToColName(name);
        }
        return colName;
    }

    public void setColName(String colName) {
        this.colName = colName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isPk() {
        return isPk;
    }

    public void setPk(boolean pk) {
        isPk = pk;
    }

    public boolean isNotNull() {
        return notNull;
    }

    public void setNotNull(boolean notNull) {
        this.notNull = notNull;
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    public Integer getLength() {
        return length;
    }

    public void setLength(Integer length) {
        this.length = length;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }

    public boolean isEncrypt() {
        return encrypt;
    }

    public void setEncrypt(boolean encrypt) {
        this.encrypt = encrypt;
    }

    // ================== Object 方法 ==================

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ModelField that = (ModelField) o;
        return Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name);
    }

    @Override
    public String toString() {
        return "ModelField{" +
                "name='" + name + '\'' +
                ", colName='" + getColName() + '\'' +
                ", type='" + type + '\'' +
                ", isPk=" + isPk +
                ", notNull=" + notNull +
                '}';
    }
}
